
exports.responseMessages = {
    PARAMETER_MISSING       : "PARAMETER_MISSING",
    LOCK_MANUALLY           : "LOCK_MANUALLY",
    SOMETHING_WENT_WRONG    : "SOMETHING_WENT_WRONG",
    SUCCESS                 : "SUCCESS",
    SHOW_ERROR_MESSAGE      : "SHOW_ERROR_MESSAGE",
    ERROR_IN_EXECUTION      : "ERROR_IN_EXECUTION",
    ASSET_ID_ALREADY_EXISTS : "ASSET_ID_ALREADY_EXISTS",
    DEVICE_ID_ALREADY_EXISTS: "DEVICE_ID_ALREADY_EXISTS",
    QR_CODE_ALREADY_EXISTS  : "QR_CODE_ALREADY_EXISTS",
    DEVICE_TYPE_NOT_EXIST   : "DEVICE_TYPE_NOT_EXIST",
    TRACKER_ID_NOT_EXIST    : "TRACKER_ID_NOT_EXIST",
    DEVICE_TYPE_INACTIVE    : "DEVICE_TYPE_INACTIVE",
    DEVICE_ID_NOT_EXIST     : "DEVICE_ID_NOT_EXIST",
    ASSET_ID_NOT_EXIST      : "ASSET_ID_NOT_EXIST",
    BUSINESS_INACTIVE       : "BUSINESS_INACTIVE",
    JOB_ALREADY_EXISTS      : "JOB_ALREADY_EXIST",
    JOB_ASSIGNED            : "JOB_ASSIGNED_SUCCESSFUL",
    JOB_ACTION_COMPLETED    : "JOB_ACTION_COMPLETED",
    JOB_FAILED              : "JOB_ALREADY_FAILED",
    INVALID_ACTION          : "INVALID_ACTION",
    LOCK_ALREADY_IN_REQUESTED_STATE : "LOCK_ALREADY_IN_REQUESTED_STATE",
    KEY_ERROR               : "KEY_ERROR"
};

exports.responseFlags = {
  SUCCESS              : 200,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST          : 400,
  CLIENT_ERROR         : 401,
  SHOW_ERROR_MESSAGE   : 201,
  ERROR_IN_EXECUTION   : 404
};

